# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAjp4SVLUktXgVb-bmmqsCmCW--PUnaI
"""

import numpy as np
import pandas as pd

student_data = [
    [100, 90, 10],
    [90, 70, 7],
    [120, 100, 14],
    [80, 50, 2]
]
df = pd.DataFrame(student_data, columns=['iq', 'marks', 'package', ])
print(df)

df.columns = ['a', 'b', 'c']
df

student_dict = {
'iq': [100, 90, 80, 120, 0, 0],
'marks': [80, 70, 100, 90, 0, 0],
'package': [10, 7, 14, 2, 0, 0],
}
students = pd.DataFrame(student_dict)
students

students[('iq')]

data = pd.read_csv("/content/ms_harga_harian.csv")
data

print(data.shape)
print(data.columns)

data.head(8)

data.tail()

data[8:18]

(df5000['kode_cabang'].unique())

data['tambahan_modal'] = data['modal_cabang'] + 5000

sum(data[(data['kode_produk'] == "PROD-0000001")][('harga_berlaku_cabang')])

data.head()

produk = pd.read_csv('/content/ms_produk.csv')
produk